export const magazineArticles = [
  // DESTAQUES (Slider Superior - Tirados de "destaques 2025" / Entrevistas)
  { category: "Campeão", title: "Cris Nieiro: Três Dias, Três Prêmios", desc: "Venceu a Tattoo Week e All Stars Miami no mesmo fim de semana.", imageUrl: "/assets/highlight-cris.jpg", isHighlight: true },
  { category: "Perfil", title: "Julio: O Legado de um Mestre", desc: "A história e as técnicas que consolidaram seu nome na indústria.", imageUrl: "/assets/highlight-julio-portrait.jpg", isHighlight: true },
  { category: "Destaque", title: "Ana Velho: Uma Lenda Brasileira", desc: "A força e a história de uma das maiores tatuadoras do país.", imageUrl: "/assets/legend-ana-velho.jpg", isHighlight: true },
  { category: "Prêmio", title: "Vitória Histórica do Brasil em Milão", desc: "Tatuadores brasileiros conquistam os prêmios máximos na Milano Tattoo Convention.", imageUrl: "/assets/highlight-milano.jpg", isHighlight: true },
  { category: "Internacional", title: "O Triunfo na França: Mondial de la Tatouage", desc: "A conquista de prêmios no evento mais prestigiado da Europa.", imageUrl: "/assets/highlight-mondial-cover.jpg", isHighlight: true },
  
  // ARTIGOS DA HISTORY.HTML
  { category: "Origins", title: "O Significado Sagrado da Tatuagem Polinésia", desc: "Uma viagem profunda às raízes tribais e o significado de cada símbolo.", imageUrl: "/assets/history-tribal.png", isHighlight: true },
  { category: "Brasil", title: "História da Tatuagem no Brasil", desc: "A evolução da arte na pele em terras brasileiras.", imageUrl: "/assets/brazil-history.png", isHighlight: true },
  { category: "Raízes Profundas", title: "A Origem da Tatuagem: Marcas Milenares", desc: "Como as primeiras marcas foram feitas e seu propósito.", imageUrl: "/assets/origin-tattoo.png", isHighlight: false },
  { category: "Revolução Visual", title: "Da Pele às Galerias: A Nova Era", desc: "O reconhecimento definitivo da tatuagem como arte.", imageUrl: "/assets/gallery-modern.png", isHighlight: false },
  { category: "História", title: "Dr. Fukushi Masaichi: O Guardião das Peles", desc: "A incrível coleção de peles tatuadas preservadas.", imageUrl: "/assets/history-fukushi-real.jpg", isHighlight: false },
  { category: "Pioneira", title: "Jessie Knight: A Dama da Agulha", desc: "A primeira mulher a tatuar profissionalmente no Reino Unido.", imageUrl: "/assets/legend-jessie.jpg", isHighlight: false },
  { category: "Realeza", title: "George Burchett: O Rei dos Tatuadores", desc: "Atravessou guerras, reis e culturas.", imageUrl: "/assets/legend-burchett.jpg", isHighlight: false },
  { category: "Lenda Viva", title: "Sailor Jerry: O Pai do Old School", desc: "Seus flashs definiram uma era inteira.", imageUrl: "/assets/legend-sailor.png", isHighlight: false },
  { category: "Ancestralidade", title: "Whang-od: A Última Mambabatok", desc: "Guardiã da tradição filipina nas montanhas.", imageUrl: "/assets/whang-od.png", isHighlight: false },
  { category: "Mestre", title: "Horiyoshi III: A Alma do Japão", desc: "Mestre supremo do Irezumi japonês.", imageUrl: "/assets/legend-irezumi.png", isHighlight: false },
  { category: "Inovação", title: "Filip Leu: O Dragão Psicodélico", desc: "Pioneiro do estilo biomecânico e grandes composições.", imageUrl: "/assets/legend-leu.png", isHighlight: false },
  { category: "Ícone Pop", title: "Lyle Tuttle: O Tatuador das Estrelas", desc: "Levou a arte das ruas para a capa da Rolling Stone.", imageUrl: "/assets/legend-lyle.png", isHighlight: false },
  { category: "Padrinho", title: "Ed Hardy: O Rei do Tattoo Wear", desc: "Uniu o Oriente e o Ocidente na tatuagem moderna.", imageUrl: "/assets/legend-edhardy-real.jpg", isHighlight: false }
];

// O script gerou os artistas a partir da pasta. Vamos injetá-los diretamente aqui.
export const featuredArtists = [
  { "name": "Alemão", "years": "Tradição", "desc": "Respeito Absoluto.", "imageUrl": "/fotos artistas/Alemão.jpg", "category": "Lendas" },
  { "name": "Ami James", "years": "1972 - Presente", "desc": "Miami Ink.", "imageUrl": "/fotos artistas/Ami James.jpeg", "category": "Mestres" },
  { "name": "Amund Dietzel", "years": "1891–1974", "desc": "O mestre silencioso de Milwaukee", "imageUrl": "/fotos artistas/Amund Dietzel.jpg", "category": "Era de Ouro" },
  { "name": "beicinho", "years": "Ícone", "desc": "Velha Guarda.", "imageUrl": "/fotos artistas/beicinho.jpg", "category": "Lendas" },
  { "name": "Bert Grimm", "years": "Pioneiro", "desc": "American Traditional.", "imageUrl": "/fotos artistas/Bert Grimm.jpg", "category": "Era de Ouro" },
  { "name": "Beto Satan", "years": "Pioneiro", "desc": "Rock n Roll.", "imageUrl": "/fotos artistas/Beto Satan.jpg", "category": "Lendas" },
  { "name": "Betty Broadbent", "years": "1909–1983", "desc": "A mulher que levou a tatuagem ao mundo", "imageUrl": "/fotos artistas/Betty Broadbent.jpg", "category": "Era de Ouro" },
  { "name": "bobtyrell", "years": "1962 - Presente", "desc": "Realismo preto e cinza.", "imageUrl": "/fotos artistas/bobtyrell.jpg", "category": "Mestres" },
  { "name": "bruxo", "years": "Mítico", "desc": "Underground.", "imageUrl": "/fotos artistas/bruxo.jpg", "category": "Lendas" },
  { "name": "cap coleman", "years": "1884–1973", "desc": "O padrinho da tatuagem americana", "imageUrl": "/fotos artistas/cap coleman.jpg", "category": "Era de Ouro" },
  { "name": "Carolina Caosvalle", "years": "Contemporâneo", "desc": "Artista internacional, com linguagem autoral.", "imageUrl": "/fotos artistas/Carolina Caosvalle.jpg", "category": "Ranking" },
  { "name": "Charlie Wagner", "years": "Pioneiro", "desc": "Pioneiro da tatuagem elétrica.", "imageUrl": "/fotos artistas/Charlie Wagner.jpg", "category": "Era de Ouro" },

  { "name": "Chico Morbene", "years": "Contemporâneo", "desc": "Nome tradicional da tatuagem brasileira, reconhecido como referência.", "imageUrl": "/fotos artistas/Chico Morbene.jpg", "category": "Ranking" },
  { "name": "Cliff Raven", "years": "1932–2001", "desc": "A ponte entre o Japão e o Ocidente", "imageUrl": "/fotos artistas/Cliff Raven.jpg", "category": "Era de Ouro" },
  { "name": "Cris Niero", "years": "Contemporâneo", "desc": "Artista brasileiro com trabalho consistente.", "imageUrl": "/assets/highlight-cris.jpg", "category": "Ranking" },
  { "name": "Coimbra", "years": "Contemporâneo", "desc": "Tatuador brasileiro com identidade visual forte.", "imageUrl": "/fotos artistas/Coimbra.jpg", "category": "Ranking" },
  { "name": "Diego Nunes", "years": "Contemporâneo", "desc": "Nome ativo da tatuagem brasileira.", "imageUrl": "/fotos artistas/Diego Nunes.jpg", "category": "Ranking" },
  { "name": "Dung Tran", "years": "Contemporâneo", "desc": "Artista vietnamita reconhecido mundialmente pelo realismo.", "imageUrl": "/fotos artistas/Dung Tran.jpg", "category": "Ranking" },
  { "name": "Estopa", "years": "1950 - 2020", "desc": "Lenda Biker.", "imageUrl": "/fotos artistas/Estopa.jpg", "category": "Lendas" },
  { "name": "Fabricio Galdino", "years": "Contemporâneo", "desc": "Tatuador brasileiro com estilo sólido.", "imageUrl": "/fotos artistas/Fabricio Galdino.jpg", "category": "Ranking" },
  { "name": "foto triz", "years": "Contemporâneo", "desc": "Mestre da Tatuagem", "imageUrl": "/fotos artistas/foto triz.jpg", "category": "Mestres" },
  { "name": "freddy negrete", "years": "1956 - Presente", "desc": "Lenda do Chicano.", "imageUrl": "/fotos artistas/freddy negrete.jpg", "category": "Mestres" },
  { "name": "Ganso Galvão", "years": "Contemporâneo", "desc": "Referência do blackwork no Brasil.", "imageUrl": "/fotos artistas/Ganso Galvão —.jpg", "category": "Ranking" },
  { "name": "guy atkson", "years": "1968 - Presente", "desc": "Bio-orgânico.", "imageUrl": "/fotos artistas/guy atkson.jpg", "category": "Mestres" },
  { "name": "Henk Schiffmacher", "years": "1952 - Presente", "desc": "Hanky Panky.", "imageUrl": "/fotos artistas/Henk Schiffmacher.jpg", "category": "Mestres" },
  { "name": "Hernan Yepes", "years": "Contemporâneo", "desc": "Artista latino-americano com reconhecimento internacional.", "imageUrl": "/fotos artistas/Hernan Yepes.jpg", "category": "Ranking" },
  { "name": "Horiyasu", "years": "1953 - Presente", "desc": "Mestre Tebori.", "imageUrl": "/fotos artistas/Horiyasu.jpg", "category": "Mestres" },
  { "name": "Horst Streckenbach", "years": "1925–2001", "desc": "O engenheiro da tatuagem", "imageUrl": "/fotos artistas/Horst Streckenbach.jpg", "category": "Era de Ouro" },
  { "name": "Ibrahim Barboza", "years": "Contemporâneo", "desc": "Tatuador brasileiro com trabalho consistente.", "imageUrl": "/fotos artistas/Ibrahim Barboza.jpg", "category": "Ranking" },
  { "name": "Inácio da Glória", "years": "Pioneiro", "desc": "Ética Profissional.", "imageUrl": "/fotos artistas/Inácio da Glória.jpg", "category": "Lendas" },
  { "name": "Jacci Gresham", "years": "1951– ", "desc": "Resistência e representatividade", "imageUrl": "/fotos artistas/Jacci Gresham.jpg", "category": "Era de Ouro" },
  { "name": "jack rudy", "years": "1954 - Presente", "desc": "Pai do Fine Line.", "imageUrl": "/fotos artistas/jack rudy.jpg", "category": "Mestres" },
  { "name": "Javi Tattooedtheory", "years": "Contemporâneo", "desc": "Artista e pensador da tatuagem.", "imageUrl": "/fotos artistas/Javi Tattooedtheory.jpg", "category": "Ranking" },
  { "name": "Joybacks Morales", "years": "Contemporâneo", "desc": "Artista latino-americano com estilo próprio.", "imageUrl": "/fotos artistas/Joybacks Morales.jpg", "category": "Ranking" },
  { "name": "Julian Siebert", "years": "Contemporâneo", "desc": "Artista alemão.", "imageUrl": "/fotos artistas/Julian Siebert.jpg", "category": "Ranking" },
  { "name": "Junko Shimada", "years": "1967– ", "desc": "A delicadeza que rompeu barreiras", "imageUrl": "/fotos artistas/Junko Shimada.jpg", "category": "Era de Ouro" },
  { "name": "kari barba", "years": "1966– ", "desc": "A força do tradicional vivo", "imageUrl": "/fotos artistas/kari barba.jpg", "category": "Era de Ouro" },
  { "name": "Kasas Ink", "years": "Contemporâneo", "desc": "Artista internacional, composição sólida.", "imageUrl": "/fotos artistas/Kasas Ink —.jpg", "category": "Ranking" },
  { "name": "Klebyz Tattoo", "years": "Contemporâneo", "desc": "Artista brasileiro versátil.", "imageUrl": "/fotos artistas/Klebyz Tattoo.jpg", "category": "Ranking" },
  { "name": "leo zulueta", "years": "1952 - Presente", "desc": "Pai do Neo-tribal.", "imageUrl": "/fotos artistas/leo zulueta.jpg", "category": "Mestres" },
  { "name": "logo mestres", "years": "Logo", "desc": "Logo Mestres", "imageUrl": "/fotos artistas/logo mestres.png", "category": "Outros" },
  { "name": "Luiza Bello", "years": "Contemporâneo", "desc": "Tatuadora brasileira.", "imageUrl": "/fotos artistas/Luiza Bello.jpg", "category": "Ranking" },
  { "name": "Luke Atkinson", "years": "1978– ", "desc": "A nova escola europeia", "imageUrl": "/fotos artistas/Luke Atkinson.jpg", "category": "Era de Ouro" },
  { "name": "Machado Artes", "years": "Contemporâneo", "desc": "Artista brasileiro.", "imageUrl": "/fotos artistas/Machado Artes.jpg", "category": "Ranking" },
  { "name": "mark mahoney", "years": "1957– ", "desc": "A caligrafia de Hollywood", "imageUrl": "/fotos artistas/mark mahoney.jpg", "category": "Era de Ouro" },
  { "name": "martin hilderbrant", "years": "1800s", "desc": "Primeiro tatuador profissional nos EUA", "imageUrl": "/fotos artistas/martin hilderbrant.jpg", "category": "Era de Ouro" },
  { "name": "Mary Jane Haake", "years": "1951– ", "desc": "A tatuagem como prática profissional", "imageUrl": "/fotos artistas/Mary Jane Haake.jpg", "category": "Era de Ouro" },
  { "name": "Maurício Teodoro", "years": "1966 - Presente", "desc": "Mestre Oriental.", "imageUrl": "/fotos artistas/Maurício Teodoro.jpg", "category": "Lendas" },
  { "name": "Mick_Tattoo", "years": "Lenda", "desc": "Técnica Fina.", "imageUrl": "/fotos artistas/Mick_Tattoo.jpg", "category": "Lendas" },
  { "name": "Neto Coutinho", "years": "Contemporâneo", "desc": "Tatuador brasileiro com trajetória sólida.", "imageUrl": "/assets/highlight-neto-full.jpg", "category": "Ranking" },
  { "name": "Nikko Hurtado", "years": "1981 - Presente", "desc": "Realismo Colorido.", "imageUrl": "/fotos artistas/Nikko Hurtado.jpg", "category": "Mestres" },
  { "name": "Paulinho De Deus", "years": "Contemporâneo", "desc": "Nome histórico da tatuagem brasileira.", "imageUrl": "/fotos artistas/Paulinho De Deus.jpg", "category": "Ranking" },
  { "name": "Ralf Nonnweiler", "years": "Contemporâneo", "desc": "Artista alemão reconhecido.", "imageUrl": "/assets/highlight-ralf-portrait.jpg", "category": "Ranking" },
  { "name": "russo", "years": "Formador", "desc": "Mestre de Convenções.", "imageUrl": "/fotos artistas/russo.jpg", "category": "Lendas" },
  { "name": "Samuel O’Reilly", "years": "Pioneiro", "desc": "Inventor da máquina de tatuagem", "imageUrl": "/fotos artistas/Samuel O’Reilly.jpg", "category": "Era de Ouro" },
  { "name": "southland macdonald", "years": "Contemporâneo", "desc": "Mestre da Tatuagem", "imageUrl": "/fotos artistas/southland macdonald.jpg", "category": "Mestres" },
  { "name": "Steve Butcher", "years": "Contemporâneo", "desc": "Realismo contemporâneo.", "imageUrl": "/fotos artistas/Steve Butcher.jpg", "category": "Ranking" },
  { "name": "sylvio freitas", "years": "Contemporâneo", "desc": "Nome tradicional da tatuagem brasileira.", "imageUrl": "/fotos artistas/sylvio freitas.jpg", "category": "Ranking" },
  { "name": "Tampa", "years": "Contemporâneo", "desc": "Tatuador brasileiro underground.", "imageUrl": "/fotos artistas/Tampa.jpg", "category": "Ranking" },
  { "name": "tyes", "years": "Técnica", "desc": "Influência Direta.", "imageUrl": "/fotos artistas/tyes.jpg", "category": "Lendas" },
  { "name": "tyrone", "years": "Internacional", "desc": "Black & Grey.", "imageUrl": "/fotos artistas/tyrone.jpg", "category": "Lendas" },
  { "name": "Ubiratam", "years": "Contemporâneo", "desc": "Tatuador brasileiro ligado à tradição.", "imageUrl": "/fotos artistas/Ubiratam.jpg", "category": "Ranking" },
  { "name": "Vitoria Lee", "years": "Contemporâneo", "desc": "Artista internacional, técnica refinada.", "imageUrl": "/fotos artistas/Vitoria Lee.jpg", "category": "Ranking" },
  { "name": "Yomico Moreno", "years": "Contemporâneo", "desc": "Artista venezuelano global.", "imageUrl": "/fotos artistas/Yomico Moreno.jpg", "category": "Ranking" },
  { "name": "Zakarov", "years": "Contemporâneo", "desc": "Artista internacional, estética intensa.", "imageUrl": "/fotos artistas/Zakarov.jpg", "category": "Ranking" },
  { "name": "Ítalo Santos", "years": "Contemporâneo", "desc": "Tatuador brasileiro com atuação contínua.", "imageUrl": "/fotos artistas/Ítalo Santos.jpg", "category": "Ranking" }
];

export const registeredEvents = [
  {
    id: "vale-ink-2026",
    title: "VALE INK TATTOO FESTIVAL",
    date: "21 - 23 Agosto 2026",
    startDate: "2026-08-21",
    venue: "Farma Conde Arena",
    city: "São José dos Campos",
    country: "Brasil",
    desc: "O principal encontro de tatuadores do Vale do Paraíba, com muita cultura e lifestyle.",
    imageUrl: "/cartazes eventos/valeink cartaz.jpeg"
  },
  {
    id: "masters-ink-2026",
    title: "MASTERS INK TATTOO FESTIVAL",
    date: "18 - 20 Setembro 2026",
    startDate: "2026-09-18",
    venue: "Expo Center",
    city: "São Paulo",
    country: "Brasil",
    desc: "Um festival focado nos maiores mestres e tendências do mundo da tatuagem.",
    imageUrl: "/cartazes eventos/masters ink cartaz.jpeg"
  },
  {
    id: "canoas-tattoo-2026",
    title: "CANOAS TATTOO EXPO",
    date: "2 - 4 Outubro 2026",
    startDate: "2026-10-02",
    venue: "Centro de Eventos",
    city: "Canoas",
    country: "Brasil",
    desc: "A maior convenção de tatuagem da região, reunindo grandes artistas nacionais e internacionais.",
    imageUrl: "/cartazes eventos/canoas cartaz.jpeg"
  },
  {
    id: "tattoo-week-2026",
    title: "TATTOO WEEK",
    date: "20 - 22 Novembro 2026",
    startDate: "2026-11-20",
    venue: "Expo Center Norte",
    city: "São Paulo",
    country: "Brasil",
    desc: "A maior convenção de tatuagem do mundo! Três dias insanos de muita arte, shows e competições.",
    imageUrl: "/cartazes eventos/tattooweek cartaz.jpeg"
  }
];

export const registeredVideos = [
  { id: "v1", title: "InkDoc Netflix", file: "inkdoc-netflix.mp4" },
  { id: "v2", title: "La Roche Posay", file: "la-roche-posay.mp4" },
  { id: "v3", title: "Mondial Video", file: "mondial-video.mp4" },
  { id: "v4", title: "Planet Tattoo", file: "planet-tattoo.mp4" },
  { id: "v5", title: "Tattoo Week", file: "tattoo-week.mp4" }
];
